### ISSUE TITLE
Mettre une police personnalisée

### ISSUE THREAD

**Issue by homermafia** [DiscowZombie/MadRunner#35]
Pour corriger l'issue #5 , on pourrait utiliser un font personnalisé avec `pygame.font.Font()` au lieu d'utiliser `pygame.font.SysFont()`, au moins, le texte sera comme prévu quelque soit le PC.

**Comment by DiscowZombie** [comment]
Work since #37 (e46c9505f3246b67defd6c4aed395858d981bd79)
